### ISSUE TITLE
Post type selector 1.8.7

### ISSUE THREAD

**Issue by sazonische** [motopress/getwid#107]
The post type selector does not show the campaign type from the leyka plugin.
wp: [https://ru.wordpress.org/plugins/leyka/](https://ru.wordpress.org/plugins/leyka/)
git: [https://github.com/Teplitsa/Leyka](https://github.com/Teplitsa/Leyka)
On version 1.8.6 everything works correctly.

If you change the priority to 0, the post appears in the list of record types.
link to pos: [https://github.com/Teplitsa/Leyka/blob/master/inc/leyka-core.php#L88](https://github.com/Teplitsa/Leyka/blob/master/inc/leyka-core.php#L88)
![campaign](https://github.com/motopress/getwid/assets/7954312/0a5d29c4-28ab-4edf-af19-d767a92ac4c1)

**Comment by sazonische** [comment]
This is also a problem with the Event [Organiser plugin](https://wordpress.org/plugins/event-organiser/)

**Comment by Endzevich** [comment]
Fixed in #109
