### ISSUE TITLE
JSON-Error when updating pages

### ISSUE THREAD

**Issue by errotu** [motopress/getwid#62]
First, thank you for the great collection of blocks. It really makes my life easier!

Unfortunately, however, whenever I update a page which contains Getwid-Blocks, it actually saves the page, but throws out the error: "The response is not a valid JSON response."

The error seems to related to the interplay of WP User Frontend and Getwid (see https://github.com/weDevsOfficial/wp-user-frontend/issues/1248). Do you have any thoughts what could be the reason?

**Comment by Endzevich** [comment]
Hello there, unfortunately, we were unable to replicate the described issue under different conditions. Kindly submit your request to our Help Desk providing your website URL and temporary access to WordPress dashboard, so we take a closer look at the issue.

**Comment by errotu** [comment]
Hey, thank you for your help proposal. I've done some further investigation and it doesn't seem to be related to Getwid. [It seems to be the WP External Links plugin](https://github.com/weDevsOfficial/wp-user-frontend/issues/1248#issuecomment-1068278279) (maybe only in its interplay with WPUF). For the moment, it's solved for me. Sorry for the trouble!
